spring.datasource.url=jdbc:mysql://localhost:3306/travel_manager
spring.datasource.username=root
spring.datasource.password=Mrcoolyp@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# WeatherAPI.com key
weather.api.key=095409d0c20a42ea875173737260504

# WAQI API key
aqi.api.key=d5125ff9367085d72b44da0f044049b7f09c4a84

# Groq Configuration (Using OpenAI-style format)
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant